# Name shown in the "Actions" tab
name: My First Workflow

# We can write the events in two ways
# on:
#   push:
#   workflow_dispatch:
on: [push, workflow_dispatch]

# â“ can I have an action without jobs?
# ğŸ’¡ no, it throws an error.

jobs:
  # ğŸ¤” can I call my job anything or is there a requirement?
  my-first-job:
    runs-on: ubuntu-latest
    # ğŸ¤” can I have a job without steps?
