# Name shown in the "Actions" tab
# name: My First Workflow

# We can write the events in two ways
# on:
#   push:
#   workflow_dispatch:
on: [push, workflow_dispatch]

# â“ can I have an action without jobs?
# ğŸ’¡ no. a job is required and it must have steps. else it throws an error.

# â“ can I call my job anything or is there a requirement?
# ğŸ’¡ yes. it's displayed in the single action screen, eg. https://github.com/ekafyi/hello-gh-actions/actions/runs/836142989

jobs:
  # ğŸ¤” 
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
